const blogs = [
    {
        'id': 'cp-08',
        'slug': 'cp-08',
        'title': 'Path from Root to Node in Binary Tree',
        'description': 'Competitive Programming Problem: Find the Path of a node from the root in a binary tree',
        'date': '2025-07-02',
        'domains': ['competitive-programming', 'tree', 'dfs', 'binary-tree'],
        'filename': 'cp-08.md',
    },
    {
        'id': 'cp-07',
        'slug': 'cp-07',
        'title': 'Left & Right View of a Binary Tree',
        'description': 'Competitive Programming Problem: Find the left & right view of a binary tree',
        'date': '2025-07-02',
        'domains': ['competitive-programming', 'tree', 'bfs', 'binary-tree'],
        'filename': 'cp-07.md',
    },
    {
        'id': 'system-design-03',
        'slug': 'system-design-03',
        'title': '03: System Design - Scalability',
        'description': 'Third post in the system design series, focusing on scalability techniques.',
        'date': '2025-07-01',
        'domains': ['system-design'],
        'filename': 'system-design-03.md',
    },
    {
        'id': 'cp-06',
        'slug': 'cp-06',
        'title': 'Tree Traversal - Inorder, Preorder, Postorder',
        'description': 'Competitive Programming Problem: Implement Tree Traversal methods - Inorder, Preorder, Postorder',
        'date': '2025-07-01',
        'domains': ['competitive-programming', 'tree', 'dsa', 'dfs', 'binary-tree'],
        'filename': 'cp-06.md',
    },
    {
        'id': 'cp-05',
        'slug': 'cp-05',
        'title': 'Min Stack',
        'description': 'Competitive Programming Problem: Implement Min Stack',
        'date': '2025-06-23',
        'domains': ['competitive-programming', 'stack'],
        'filename': 'cp-05.md',
    },
    {
        'id': 'cp-04',
        'slug': 'cp-04',
        'title': 'Check for Balanced Parenthesis',
        'description': 'Competitive Programming Problem: Check for Balanced Parenthesis',
        'date': '2025-06-21',
        'domains': ['competitive-programming', 'stack'],
        'filename': 'cp-04.md',
    },
    {
        'id': 'cp-03',
        'slug': 'cp-03',
        'title': 'Stack - Linear Data Structure',
        'description': 'Competitive Programming Problem: Stack linear data structure implementation',
        'date': '2025-06-21',
        'domains': ['competitive-programming', 'dsa', 'stack'],
        'filename': 'cp-03.md',
    },
    {
        'id': 'math-01',
        'slug': 'math-01',
        'title': 'Probability & Expected Values',
        'description': 'A comprehensive guide to understanding probability and expected values in mathematics.',
        'date': '2025-06-21',
        'domains': ['math'],
        'filename': 'math-01.md',
    },
    {
        'id': 'cp-02',
        'slug': 'cp-02',
        'title': 'Next Greater Element',
        'description': 'Competitive Programming Problem: Find the next greater element for each element in an array.',
        'date': '2025-06-20',
        'domains': ['competitive-programming', 'stack'],
        'filename': 'cp-02.md',
    },
    {
        'id': 'system-design-02',
        'slug': 'system-design-02',
        'title': '02: System Design - Load Balancing',
        'description': 'Second post in the system design series, focusing on load balancing techniques.',
        'date': '2025-06-19',
        'domains': ['system-design'],
        'filename': 'system-design-02.md',
    },
    {
        'id': 'system-design-01',
        'slug': 'system-design-01',
        'title': '01: System Design - Introduction to System Design',
        'description': 'First post in the system design series, covering the basics of system design.',
        'date': '2025-06-19',
        'domains': ['system-design'],
        'filename': 'system-design-01.md',
    },
    {
        'id': 'cp-01',
        'slug': 'cp-01',
        'title': 'Maximum Subarray Sum',
        'description': 'Competitive Programming Problem: Find the maximum sum of a contiguous subarray.',
        'date': '2025-06-19',
        'domains': ['competitive-programming', 'dynamic-programming', 'array'],
        'filename': 'cp-01.md',
    },
]

export default blogs;